# Generated by Django 3.0.6 on 2020-06-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('user_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='web_map.UserPath')),
            ],
        ),
    ]
