# Generated by Django 3.0.6 on 2020-06-04 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=41)),
                ('car_namber', models.CharField(max_length=13)),
                ('place', models.IntegerField()),
                ('option1', models.BooleanField()),
                ('option2', models.BooleanField()),
                ('option3', models.BooleanField()),
                ('conect', models.CharField(max_length=41)),
                ('coment', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
