# Generated by Django 3.0.6 on 2020-06-04 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_map', '0002_pathpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='car_namber',
            new_name='car_number',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='coment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='conect',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='userpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
