# Generated by Django 3.0.6 on 2020-06-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_map', '0003_auto_20200604_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='option3',
            new_name='animals_allowed',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='option2',
            new_name='can_play_music',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='option1',
            new_name='can_smoke',
        ),
        migrations.AddField(
            model_name='transport',
            name='name',
            field=models.CharField(default='Без названия', max_length=255),
        ),
    ]
