# Generated by Django 3.0.6 on 2020-06-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_map', '0004_auto_20200607_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_map.Transport'),
            preserve_default=False,
        ),
    ]
